name: cargo build on linux like

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

# 即使重定向到管道文件也要ASNI颜色
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
#    - name: Run tests
#      run: cargo test --verbose
